# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_fsm
import markupfield.fields
import qraz.frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.PositiveIntegerField(verbose_name='Github repository ID')),
                ('name', models.CharField(max_length=256, verbose_name='Repository name')),
                ('state', django_fsm.FSMField(default='inactive', max_length=50)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('comment', markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True, verbose_name='Comment')),
                ('comment_markup_type', models.CharField(choices=[('', '--'), ('ReST', 'ReST')], default='ReST', max_length=30)),
                ('secret', models.CharField(default=qraz.frontend.models.get_secret, max_length=16, verbose_name='Shared secret for Github webhooks')),
                ('hook', models.PositiveIntegerField(null=True, verbose_name='ID of Github webhook')),
                ('_comment_rendered', models.TextField(editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
