# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='repository',
            name='fork',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repository',
            name='state',
            field=django_fsm.FSMField(default='inactive', max_length=50, protected=True),
        ),
    ]
