# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20160113_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('path', models.TextField()),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last modified')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Repository')),
            ],
        ),
    ]
